server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/bitmoi
    username: root
    password: password
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
jwt:
  secret: Y29kZXN0YXRlcy1iaXRodW1iLW1zYS10ZWFtLW1lbWJlci1zcHJpbmctYm9vdC13ZWJmbHV4LWp3dC1zZWNyZXQ
  accessExpires: 7200000 #2시간 ms
  refreshExpires: 172800000 #2주 ms
